# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36725ee3fca0b4e743e6769d95aba39f6dacf5753f6d76a925924a8477c89c8f0c00956921247e3b5f56b0720f4297088ecb27dfbcbfe78c4de3b0d8f31c792a

test:
  secret_key_base: 59766cad0b8ff17c2ce35d4432aa2012899ebbb95fdc7e21ebab09671ea37e7d8138cb57b3edcc2d2097fb007172b01738a4bee92a0189610557008bc20979aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
